name: Node.js Test

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, reopened]

env:
  PORT: 3000
  MONGO_URI : mongodb+srv://trevornagaba:test-cluster-01@test-cluster-01.9dvs05n.mongodb.net

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test